# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebWqfpbbjRlAdC8X4ZqIKtXFOTut6Zw3
"""

import numpy as np
num = np.array([10,20,30])
num

import numpy as np
list1 = [x for x in range(2, 22, 2)]
list2 = [x for x in range(1, 21, 2)]
output = np.array([list1, list2])

print(output)

import numpy as np

num = np.array([5, 8, 16, 25])
num
num2 = np.arange(1, 5) * 5
num2

import numpy as np
num = np.array([[5, 8, 16, 25], [4, 6, 12, 33]])
num.dtype

import numpy as np
num = np.array([[[5, 8, 16, 25], [4, 6, 12, 33]],[[4, 5, 6, 9], [10, 13, 32, 76]]])
num.ndim

import numpy as np
num2 = np.arange(1,5)*5
num2

import numpy as np
num = np.array([5, 8, 16, 25])
num2 = np.arange(1,5)*5
np.add(num, num2)

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr.shape

# score=[85,90,78,92,88]
# 1.convert data type of score to flot
import numpy as np
score = np.array([85,90,78,92,88])
newscore = arr.astype("f")
print(newscore)
print(newscore.dtype)

#
#
#create a copy of score  named a-score and add 5 points
import numpy as np

score = np.array([85, 90, 78, 92, 88])


a_score = score.copy()


a_score += 5
print("Original score:", score)
print("Modified a_score:", a_score)

import numpy as np
grades = np.array([[87,96,70],[100,87,90],[94,77,90],[100,81,82]])

grades

grades.max()

grades.min()

grades.sum()

grades.std()

grades.mean()

grades.var()

grades.mean(axis=0)

grades.mean(axis=1)

#finding index of 80+ scores
import numpy as n
score= n.array([85, 90, 78, 92, 88])
x = np.where(score > 80)
x

import numpy as n
score= n.array([85, 90, 78, 92, 88])
score[::2], score[-3:-1], score[1:4]

import numpy as n
score= n.array([85, 90, 78, 92, 88])
score.min(),score.max(),score.mean(),score.std(),score.var(),score.sum()

import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

# very very important
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

import numpy as np

# Create a NumPy array
score = np.array([85, 90, 78, 92, 88])

# Convert the data type of the array to float
newscore = score.astype("f")

# Print the new array and its data type
print(newscore)
print(newscore.dtype)

import numpy as np

# Original array
score = np.array([85, 90, 78, 92, 88])

# Shape of the array
print("Shape:", score.shape)

# Size of the array (total number of elements)
print("Size:", score.size)

# Item size (size of one element in bytes)
print("Item size:", score.itemsize)

# Data type of the array
print("Data type:", score.dtype)

# Sorted array
sorted_score = np.sort(score)
print("Sorted array:", sorted_score)